const CHANGE_EXAMPLE_NUMBER = 'CHANGE_EXAMPLE_NUMBER';
const INCREASE_EXAMPLE_NUMBER = 'INCREASE_EXAMPLE_NUMBER';
const DECREASE_EXAMPLE_NUMBER = 'DECREASE_EXAMPLE_NUMBER';
const INCREASE_HOME_VISITS = 'INCREASE_HOME_VISITS';
const RESET_HOME_VISITS = 'RESET_HOME_VISITS';

export {
  CHANGE_EXAMPLE_NUMBER,
  INCREASE_EXAMPLE_NUMBER,
  DECREASE_EXAMPLE_NUMBER,
  INCREASE_HOME_VISITS,
  RESET_HOME_VISITS,
};
